---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - yarn global add serverless
      - yarn  # install local dependencies, which sls needs for deploying, which I dislike
  build: 
    commands: 
      - serverless deploy --package artifacts --stage "$STAGE"
