---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g serverless
  build: 
    commands: 
      - serverless deploy --package artifacts --stage "$STAGE"
