org: binhrobles
app: burst-writing-services-app
service:
  name: burst-writing-services
  org: binhrobles
  app: burst-writing-services-app

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 4000
  localstack:
    host: http://localhost:4566
    endpoints:
      # TODO: pull request for eliminating
      # https://github.com/localstack/serverless-localstack/blob/master/src/index.js#L40
      ssm: http://localhost:4566
    stages:
      - dev
    autostart: true
    lambda:
      mountCode: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-localstack

provider:
  name: aws
  region: us-west-1
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  translate:
    handler: handler.translate
    events:
      - http:
          method: get
          path: translate
    environment:
      TRANSLATE_API_KEY: ${ssm:/burst-writing/translate/api-key~true}
