org: binhrobles
service:
  name: burst-writing-services
  org: binhrobles

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  customDomain:
    domainName: burst-api.binhrobles.com
    stage: prod
    createRoute53Record: false
    endpointType: 'regional'

  serverless-offline:
    httpPort: 4000

  localstack:
    host: http://localhost:4566
    endpoints:
      # TODO: pull request for eliminating
      # https://github.com/localstack/serverless-localstack/blob/master/src/index.js#L40
      ssm: http://localhost:4566
    stages:
      - dev
    lambda:
      mountCode: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-localstack
  - serverless-domain-manager

provider:
  name: aws
  region: us-west-1
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  individually: true

functions:
  - ${file(./translate/functions.yml)}
